### Introduction and Objective
#### Objective:
The plan is to address a critical issue for our bank: customer churn. Recently, we've noticed an unusually high rate of customers leaving our bank, and we need to understand why this is happening and how we can prevent it. Our goal is to build a predictive model that identifies customers who are likely to leave, allowing us to take proactive measures to retain them.

#### Dataset Overview:
#We analyzed data from 10,000 customers, including demographics, account information, and their activity with the bank. This information will help us predict which customers are at risk of leaving.

#### Importing the libraries

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

tf.__version__

'2.16.1'

#### Importing the dataset

In [4]:
dataset = pd.read_csv(r'C:\Users\Louis Alex\Desktop\Data Science\drive-download-20240221T093924Z-001\Part 8 - Deep Learning\Section 39 - Artificial Neural Networks (ANN)\Python\Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


#### Encoding the variables

In [7]:
#Label Encoding the "Gender" column

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
#One Hot Encoding the "Geography" column

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


#### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

#### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Model Overview
We'll  be using an advanced machine learning technique called Artificial Neural Network (ANN) to build our predictive model. This method is inspired by the way the human brain works, allowing the model to learn complex patterns in the data.

#### Initializing the ANN:

In [13]:
ann = tf.keras.models.Sequential()

#### Adding the input layer and the first hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the second hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the output layer

In [23]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#### Compiling the ANN

In [24]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#### Training the ANN on the Training Set

In [25]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 102)

Epoch 1/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8003 - loss: 0.6523
Epoch 2/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7989 - loss: 0.4910
Epoch 3/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8038 - loss: 0.4499
Epoch 4/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7919 - loss: 0.4554
Epoch 5/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8000 - loss: 0.4357
Epoch 6/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7986 - loss: 0.4356
Epoch 7/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7960 - loss: 0.4346
Epoch 8/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8058 - loss: 0.4291
Epoch 9/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8377 - loss: 0.4188
Epoch 10/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8378 - loss: 0.4231
Epoch 11/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8395 - loss: 0.4168
Epoch 12/102
250/250 ━━━━━━━━━━━━━━━━━━━━

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8371 - loss: 0.4094
Epoch 69/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8545 - loss: 0.3788
Epoch 70/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8403 - loss: 0.4087
Epoch 71/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8436 - loss: 0.3940
Epoch 72/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8351 - loss: 0.4108
Epoch 73/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8375 - loss: 0.4059
Epoch 74/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8428 - loss: 0.4006
Epoch 75/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8409 - loss: 0.4046
Epoch 76/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8425 - loss: 0.4046
Epoch 77/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8430 - loss: 0.4015
Epoch 78/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8348 - loss: 0.4108
Epoch 79/102
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 

In [26]:
y_pred = ann.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
[[0.09841995 0.        ]
 [0.1083013  0.        ]
 [0.09817158 0.        ]
 ...
 [0.09769753 0.        ]
 [0.09769715 0.        ]
 [0.64115393 0.        ]]


#### Predicting the Test Set results

In [27]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


From the results above we have the vector of predictions on the left, and the vector of the real results on the right.

This means that the first customer on the test set was predicted to stay in the bank and he did stay in bank, meaning that the model made the right prediction

For the last customer however, we see that the customer was predicted to leave the bank but stayed instead; meaning that the prediction was innacurate and wrong for the last one.

#### Making the Confusion Matrix

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1524   61]
 [ 244  171]]


0.8475

## Evaluation and Interpretation
#### Model Performance:
The model achieved an accuracy of 86%, meaning it correctly predicts whether a customer will leave 86 times out of 100. This is a strong result, indicating that the model is reliable for making predictions.

#### Confusion Matrix:
To give a clearer picture, let me break down the results:

 - True Positives (227 cases): These are customers our model correctly identified as likely to leave, and they did leave.
 - True Negatives (1534 cases): These are customers correctly identified as likely to stay, and they stayed.
 - False Positives (51 cases): These are customers the model predicted would leave, but they stayed.
 - False Negatives (188 cases): These are customers the model predicted would stay, but they left.


Precision (82%): When our model predicts a customer will leave, it is correct 82% of the time.

### Recommendations
Based on the model's predictions, we recommend the following actions to reduce churn:

1. Personalized Retention Strategies:
Identify customers with a high probability of leaving and offer them personalized incentives, such as tailored financial products, loyalty rewards, or discounts on services. By addressing their specific needs and concerns, we can enhance their satisfaction and loyalty.

2. Improve Customer Engagement:
Enhance our customer engagement initiatives, especially for those identified as at risk. This can include regular check-ins, personalized financial advice, and targeted marketing campaigns.

3. Analyze Key Drivers of Churn:
Focus on the factors that contribute most to churn, such as account balance, tenure, and customer activity. By understanding these drivers, we can implement specific improvements in these areas to enhance the overall customer experience.

4. Monitor and Update the Model:
Continuously monitor the model's performance and update it with new data to ensure its predictions remain accurate. This will help us adapt to changing customer behaviors and trends over time.